### ISSUE TITLE
STATUS_ENTRYPOINT_NOT_FOUND

### ISSUE THREAD

**Issue by SevaShpun** [yy0931/sqlite3-editor#50] opened 2024-03-10 15:35 UTC
Hello. I tried to open the database and it gave me the following error.

I installed https://aka.ms/vs/17/release/vc_redist.x64.exe, but it didn’t help.

What could be the problem ?

> STATUS_ENTRYPOINT_NOT_FOUND: Failed to load VCRuntime. Please try to reinstall it by downloading and running https://aka.ms/vs/17/release/vc_redist.x64.exe (other versions can be found at https://learn.microsoft.com/en-us/cpp/ windows/latest-supported-vc-redist). If this doesn't work, please report an issue on GitHub.
(Google translation)

Screenshot:
![screen](https://github.com/yy0931/sqlite3-editor/assets/23108549/cfa95232-6eb9-4d01-9479-4937511636b4)

VSCODE version:
![2024-03-10_183309](https://github.com/yy0931/sqlite3-editor/assets/23108549/52cf87a1-31ef-422a-8bb3-7d3d34b60300)

OS: Windows 7(x64)

**Comment by yy0931** [comment] 2024-03-10 16:53
Thanks for reporting it.

It appears that the issue is not on your environment, but the extension's executable file is incompatible with Windows 7. I have not tested the extension on Windows 7 because VSCode dropped support for it.

~~You may be able to resolve the error by building the binary on your environment (follow https://marketplace.visualstudio.com/items?itemName=yy0931.vscode-sqlite3-editor#using-user-compiled-sqlite without LIBSQLITE3_FLAGS='-DSQLITE_OMIT_DEPRECATED'). However, since fixing it may be difficult and the number of Windows 7 users is likely low, I am considering dropping support for Windows 7. There are many alternative applications you can use, such as DBeaver or DBGate.~~ (edit: see the next comment)

**Comment by yy0931** [comment] 2024-03-10 17:29
I've found a likely cause; the `panic=abort` setting that I added in commit https://github.com/yy0931/sqlite3-editor/commit/61913649a4c27e8390d2fd2c672e1ee6ec6250d8#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R40 is not supported on Windows 7 according to https://users.rust-lang.org/t/windows-unwind-safety-with-abort-on-panic/85587. I'll revert that change.

**Comment by yy0931** [comment] 2024-03-11 06:14
Resolved in version 1.0.182.

**Comment by SevaShpun** [comment] 2024-03-11 15:36
Updated to version 1.0.182. Restarted VSCODE. When opening the database, an error appears in the lower right corner of the screen.

I clicked "Send error report", the window is closed and nothing happens. The same goes for the "Close" button. The window closes and nothing happens :(

![screen1](https://github.com/yy0931/sqlite3-editor/assets/23108549/ebf226d6-af7e-4397-ab30-800f5cd54f1d)

**Comment by yy0931** [comment] 2024-03-11 17:59
It seems the newer versions of the Rust compiler has added a dependency on Windows API that does not exist on Windows 7 (namely ProcessPrng).
I think that is this commit made 2 weeks ago.
https://github.com/rust-lang/rust/commit/08caefbb103d1809113172d16eaf8f66c2edc2f1
I could run the old build of version 173 on Windows 7, but rebuilding the same commit now produces a binary that raises an error saying "ProcessPrng could not be located in bcryptprimitives.dll," even though Cargo.lock is committed to the repository.

**Comment by SevaShpun** [comment] 2024-03-11 19:42
**Version 173 works!**

Does this mean that I can no longer update to a newer version in the future? Will I only use version 173?

**Comment by yy0931** [comment] 2024-03-12 05:13
I believe we can fix the issue by setting a compilation option to make [`target_vendor = "win7"`](https://github.com/rust-lang/rust/commit/08caefbb103d1809113172d16eaf8f66c2edc2f1#diff-841dc2b8dfb6e9d7b45ac6f09eee08a8b4b6d8a2d4d921d9349f4f8f57376b5cR326) true. I'll try it later.

**Comment by SevaShpun** [comment] 2024-03-12 15:11
> I believe we can fix the issue by setting a compilation option to make [`target_vendor = "win7"`](https://github.com/rust-lang/rust/commit/08caefbb103d1809113172d16eaf8f66c2edc2f1#diff-841dc2b8dfb6e9d7b45ac6f09eee08a8b4b6d8a2d4d921d9349f4f8f57376b5cR326) true. I'll try it later.

Thank you. I'll be waiting for this update. :+1:

**Comment by yy0931** [comment] 2024-03-13 13:52
I've modified the compilation flags in https://github.com/yy0931/sqlite3-editor/commit/8054166a02ff3df557eb106618740dcd05895a8c and released version 1.0.183.

**Closed as completed by yy0931** 2024-03-13 13:52 UTC

**Comment by SevaShpun** [comment] 2024-03-13 16:10
> I've modified the compilation flags in [8054166](https://github.com/yy0931/sqlite3-editor/commit/8054166a02ff3df557eb106618740dcd05895a8c) and released version 1.0.183.

Now everything works! Thank you very much! :+1: :+1: :+1:
